= Pivotal Session Stores
Pivotal AppSuite
:toc: preamble
:toclevels: 2
:!toc-title:
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:linkattrs:
:uri-session-flush-valve: link:src/main/java/io/pivotal/appsuite/tomcat/SessionFlushValve.java

This document describes configuration common to implementations based on this framework.

== Stores

Stores are configured in the Tomcat `context.xml` via a `Manager/Store` element.

Example: _Configure a Store_
[source,xml]
----
<Context>
    <Manager className="org.apache.catalina.session.PersistentManager">
        <Store className="com.widgets.MyWidgetStore" />
    </Manager>
----

== Store Properties

Store properties are configured as attributes of the `Manager/Store` element.

Example: _Configure a Store Property_
[source,xml]
----
<Context>
    <Manager className="org.apache.catalina.session.PersistentManager">
        <Store className="com.widgets.MyWidgetStore"
               myProperty="myPropertyValue" />
    </Manager>
----

=== Session Flush Valve

property:: `sessionFlushValveEnabled`
default:: `false`

A store can be configured with a request pipeline valve that flushes sessions to the store after an HTTP request.
If the Tomcat node is a standalone instance or is a member of a Tomcat cluster, this property should be `false`.

If the store is being used to effect a cluster of Tomcat nodes, then set this property to `true`.

When enabled, a `INFO` log message is output when the store is initialized:
[source]
----
Enabling session flush valve
----

=== BackendSpy

property:: `backendSpyEnabled`
default:: `false`

A store can be configured with a spy that instruments call timings of the store's backend.
This feature can be useful in development and debugging environments.

When enabled, a `INFO` log message is output when the store is initialized:
[source]
----
Enabling backend spy
----

Example: _Backend spy log messages_
[source]
----
MyWidget initializing [0.042244ms]
MyWidget starting [14.811164ms]
MyWidget getting 504C6FB40ACE8133A530B669EEAEE290 [18.807324ms]
MyWidget getting 504C6FB40ACE8133A530B669EEAEE290 [0.302948ms]
MyWidget putting 6656EFBF10EB556838BA76AF1A759AFB [8.86287ms]
MyWidget putting 6656EFBF10EB556838BA76AF1A759AFB [0.490239ms]
MyWidget stopping [0.669562ms]
----

NOTE: the backend spy uses the logger named by the backend's class name.
