= Developing Pivotal Tomcat Session Managers
Pivotal AppSuite
:toc: preamble
:toclevels: 2
:!toc-title:
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:uri-project-contributor: link:CONTRIBUTOR{outfilesuffix}

This document overviews how to develop core and backend features.
For more specific details, please read the core's Javadocs.

If you wish to contribute to the project, please be sure to read the {uri-project-contributor}[contributor] guidelines.

== Overview

The `tomcat` sub-project defines a `BackendStore`, an abstract implementation of `org.apache.catalina.Store`, providing:

* Tomcat configuration hooks
* Tomcat lifecycle support
* Thread-safety
* JMX support

The `tomcat` sub-project also specifies an interface used by the `BackendStore` to persist sessions,
`Backend` (`Backend`).

== Backends

=== Gradle Setup

Backends are implemented as Gradle sub-projects.

To create a new backend, create a Gradle sub-project directory:

[source,sh]
----
% mkdir mybackend
----

Stub a `build.gradle` file:

[source,sh]
----
% cat <<EOF >mybackend/build.gradle
dependencies {
    compile project(':tomcat')
}
EOF
----

Add the sub-project to the root project:
[source,sh]
----
% echo "include 'mybackend'" >>settings.gradle
----

Assemble the new backend:
[source,sh]
----
% ./gradlew :mybackend:assemble
----

To change the default name of the backend as returned by `getDescription()`, add something like the following to
the backend's `build.gradle`:

[source,sh]
----
% cat <<EOF >mybackend/build.gradle
shadowJar {
    manifest {
        attributes(
                'Implementation-Title': 'My Backend',
        )
    }
}EOF
----


=== Implementation

A Backend provides concrete implementations of a `BackendStore` and a `Backend`.

At a minimum, the concrete `BackendStore` implements `getBackend()`, returning the concrete `Backend` to be used.

The concrete `BackendStore` may optionally implement setters for Java bean properties,
allowing the store to be configured at runtime by Tomcat.  Bean property values are specified in `context.xml` as
`Store` element attributes.

The `BackendStore` implementation is configured in Tomcat in the instance's `conf/context.xml`.

The `BackendStore` class is specified as the `className` attribute on a `Store` element:

[source,xml]
----
<Context>
  ...
  <Manager className="org.apache.catalina.session.PersistentManager">
    <Store className="io.pivotal.appsuite.tomcat.mybackend.MyBackendStore" />
  </Manager>
  ...
</Context>
----

Tomcat treats `Store` element attributes as Java bean properties.  To support configuration of a store property,
implement a Java bean setter in the store implementation.

For example, to support configuration of a store's hostname, in the store implemenation:

[source,java]
----
    private String host;

    public void setHost(String host) {
        this.host = host;
    }
----

When Tomcat starts, the store specified by `className` is constructed.  Any configured properties are passed to the store via
the setters.  After the properties have beens set, calls to `init()` and then `start()` ensue.

When Tomcat stops, the store's `stop()` is called before Tomcat exits.

Once a store is started, if a property is changed, the store will be stopped and a new store instance will be
constructed, repeating the above cycle.

`Store` implementations should use `init()` to do any final configuration, `start()` to acquire resources,
and `stop()` to relinquish resources.

== IDE Support

=== IntelliJ

[source,sh]
----
% ./gradlew idea
----

In IntelliJ, select _File->Open..._ and select the project directory.

If prompted, _Import Gradle project_ to enable the _Gradle Tool Window_.  Using the default options should work, although a JDK 7 for the _Gradle JVM_ is recommended.

=== Eclipse

[source,sh]
----
% ./gradle eclipse
----

_These instructions work for Eclipse Neon._

In Eclipse, select _File->Open Projects from File System..._ and select the project directory.  Deselect the top-level project, then click _Finish_ to import the sub-projects.
