= Pivotal Tomcat Session Stores
Pivotal AppSuite
:toc: preamble
:toclevels: 2
:!toc-title:
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:linkattrs:
:uri-project-build: link:BUILD{outfilesuffix}
:uri-project-developer: link:DEVELOPER{outfilesuffix}
:uri-project-tomcat: link:tomcat/README{outfilesuffix}
:uri-project-jedis: link:jedis/README{outfilesuffix}
:uri-apache-license: http://www.apache.org/licenses/LICENSE-2.0

This project provides implementations of Tomcat session stores.

== Goals

* Provide a framework for implementing Apache Tomcat session stores
* Provide Apache Tomcat session store implementations for popular data stores

== Store Help

{uri-project-tomcat}[Common Help]::
Redis server and cluster support using the Jedis client libraries.

{uri-project-jedis}[Redis (via Jedis) Help]::
Redis server and cluster support using the Jedis client libraries.

== Building/Developing

Quick start:
[source,sh]
----
% git clone https://github.com/pivotalsoftware/session-managers
% cd session-managers
% ./gradlew assemble
----

For more details on building, see the {uri-project-build}[build] documentation.

For more details on developing core features and additional stores, see the {uri-project-developer}[developer] documentation.

== License

Free use of this project is granted under the terms of the {uri-apache-license}["Apache License, Version 2.0", window="_blank"]
