= Pivotal Redis Session Stores (using Jedis)
Pivotal AppSuite
:toc: preamble
:toclevels: 2
:!toc-title:
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:linkattrs:
:uri-jedis: https://github.com/xetorthio/jedis
:uri-redis: https://redis.io/
:uri-common-configuration: link:../tomcat/README{outfilesuffix}


This document describes configuration unique the Redis and Redis Cluster stores using the Jedis client.
Refer to {uri-common-configuration}[common Tomcat configuration] for general configuration help.

== Redis Store

A store using a Jedis client to connect with a Redis datastore.

className:: `io.pivotal.appsuite.tomcat.jedis.RedisStore`

Example: _Configure a Redis Store_
[source,xml]
----
<Context>
  <Manager className="org.apache.catalina.session.PersistentManager">
    <Store className="io.pivotal.appsuite.tomcat.jedis.RedisStore" />
----

=== Host Name

The Redis datastore host name.

property:: `host`
default:: `localhost`

Example: _Configure a Redis Store Host Name_
[source,xml]
----
<Context>
  <Manager className="org.apache.catalina.session.PersistentManager">
    <Store className="io.pivotal.appsuite.tomcat.jedis.RedisStore"
           host="myredishost" />
----

=== Port Number

The Redis datastore port number.

property:: `port`
default:: `6379`

Example: _Configure a Redis Store Port Number_
[source,xml]
----
<Context>
  <Manager className="org.apache.catalina.session.PersistentManager">
    <Store className="io.pivotal.appsuite.tomcat.jedis.RedisStore"
           port="16379" />
----

=== Database Number

The Redis datastore database number.

property:: `database`
default:: `0`

Example: _Configure a Redis Store Database Number_
[source,xml]
----
<Context>
  <Manager className="org.apache.catalina.session.PersistentManager">
    <Store className="io.pivotal.appsuite.tomcat.jedis.RedisStore"
           database="1" />
----

=== Password

The Redis datastore `AUTH` password.

property:: `password`
default:: _none_

Example: _Configure a Redis Store Password_
[source,xml]
----
<Context>
  <Manager className="org.apache.catalina.session.PersistentManager">
    <Store className="io.pivotal.appsuite.tomcat.jedis.RedisStore"
           password="mysecret" />
----

=== Client Connection Timeout

The Redis client connection timeout in milliseconds.

property:: `connectionTimeout`
default:: `2000`

Example: _Configure a Redis Store Client Connection Timeout_
[source,xml]
----
<Context>
  <Manager className="org.apache.catalina.session.PersistentManager">
    <Store className="io.pivotal.appsuite.tomcat.jedis.RedisStore"
           connectionTimeout="10000" />
----

=== Client Connection Pool Size

The Redis client connection pool size.

property:: `connectionPoolSize`
default:: `8`

Example: _Configure a Redis Store Client Connection Pool Size_
[source,xml]
----
<Context>
  <Manager className="org.apache.catalina.session.PersistentManager">
    <Store className="io.pivotal.appsuite.tomcat.jedis.RedisStore"
           connectionPoolSize="12" />
----

== Redis Cluster Store

A store using a Jedis cluster client to connect with a Redis datastore cluster.

className:: `io.pivotal.appsuite.tomcat.jedis.RedisClusterStore`

Example: _Configure a Redis Cluster Store_
[source,xml]
----
<Context>
  <Manager className="org.apache.catalina.session.PersistentManager">
    <Store className="io.pivotal.appsuite.tomcat.jedis.RedisClusterStore" />
----

=== Host Names and Ports

The Redis cluster host name and port pairs in comma-separated list.

property:: `hostPorts`
default:: `localhost`

Example: _Configure a Redis Cluster Store Host Names and Ports_
[source,xml]
----
<Context>
  <Manager className="org.apache.catalina.session.PersistentManager">
    <Store className="io.pivotal.appsuite.tomcat.jedis.RedisClusterStore"
           hostPorts="node0:1234,node1:4321" />
----

=== Password

The Redis cluster `AUTH` password.

property:: `password`
default:: _none_

Example: _Configure a Redis Cluster Store Password_
[source,xml]
----
<Context>
  <Manager className="org.apache.catalina.session.PersistentManager">
    <Store className="io.pivotal.appsuite.tomcat.jedis.RedisClusterStore"
           password="mysecret" />
----

=== Client Connection Timeout

The Redis cluster client connection timeout in milliseconds.

property:: `connectionTimeout`
default:: `2000`

Example: _Configure a Redis Cluster Store Client Connection Timeout_
[source,xml]
----
<Context>
  <Manager className="org.apache.catalina.session.PersistentManager">
    <Store className="io.pivotal.appsuite.tomcat.jedis.RedisClusterStore"
           connectionTimeout="10000" />
----

=== Client Connection Pool Size

The Redis cluster client connection pool size.

property:: `connectionPoolSize`
default:: `8`

Example: _Configure a Redis Cluster Store Client Connection Pool Size_
[source,xml]
----
<Context>
  <Manager className="org.apache.catalina.session.PersistentManager">
    <Store className="io.pivotal.appsuite.tomcat.jedis.RedisClusterStore"
           connectionPoolSize="12" />
----

== Utilities

Run the Gradle task `:jedis:utils` to run the project utilities.  The utilities can be used to view and modify session
mappings in the Redis datastore.

=== Usage

Run task with `-Pargs=-h` for help:

[source,sh]
----
% ./gradlew -q :jedis:utils -Pargs=-h
usage:
 -c,--config                Config file
 -C,--clear                 Clear mappings
    --database <number>     Redis database
 -h,--help                  Print this message
    --host <host>           Redis host
 -l,--list                  List mapping keys
    --password <password>   Redis password
    --port <port>           Redis port
 -R,--remove <key>          Remove a mapping
----

=== List Mapping Keys

Run task with `-Pargs=-l` to list mapping keys:

[source,sh]
----
% ./gradlew -q :jedis:utils -Pargs=-l
2152DE5BA209602E62E96AC3D54E7441
29C0217A187623FBA45322CA0A610E1B
3C9FFE5FFD846C51847B9C0864B22D7A
5F64793338C00DAFA6DE2F262FED170E
60D1B21B74566BBFB6C2334332281E72
6656EFBF10EB556838BA76AF1A759AFB
8D1FF8E87850342A18CD18CA7178ABB9
94606D96416401D43F2F85EE867EDD28
AF28F16FA1198694E44BE12A6FA9DC75
BC7C45E0185B6587B375DF6FD3A8B018
----

=== Remove Mapping

Run task with `-Pargs=-R<key>` to remove a mapping:

[source,sh]
----
% ./gradlew -q :jedis:utils -Pargs=-RBC7C45E0185B6587B375DF6FD3A8B018
mapping removed

# alternatively
% ./gradlew -q :jedis:utils -Pargs="-R BC7C45E0185B6587B375DF6FD3A8B018"
...
----

=== Clear Mappings

Run task with `-Pargs=-C` to clear mappings:

[source,sh]
----
% ./gradlew -q :jedis:utils -Pargs=-C
mappings cleared
----
