= Pivotal Redis Session Stores (using Jedis)
Pivotal AppSuite
:toc: preamble
:toclevels: 2
:!toc-title:
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:linkattrs:
:uri-jedis: https://github.com/xetorthio/jedis
:uri-redis: https://redis.io/
:uri-common-configuration: link:../tomcat/README{outfilesuffix}


This document describes configuration unique the Redis and Redis Cluster stores using the Jedis client.
Refer to {uri-common-configuration}[common Tomcat configuration] for general configuration help.

== Redis Store

A store using a Jedis client to connect with a Redis datastore.

className:: `io.pivotal.appsuite.tomcat.jedis.RedisStore`

=== Host Name

The Redis datastore host name.

property:: `host`
default:: `localhost`

=== Port Number

The Redis datastore port number.

property:: `host`
default:: `6379`

=== Database Number

The Redis datastore database number.

property:: `database`
default:: `0`

=== Password

The Redis datastore `AUTH` password.

property:: `password`
default:: _none_

=== Client Connection Timeout

The Redis client connection timeout in milliseconds.

property:: `connectionTimeout`
default:: `2000`

=== Client Connection Pool Size

The Redis client connection pool size.

property:: `connectionPoolSize`
default:: `8`

== Redis Cluster Store


A store using a Jedis cluster client to connect with a Redis datastore cluster.

className:: `io.pivotal.appsuite.tomcat.jedis.RedisClusterStore`

=== Host Names and Ports

The Redis cluster host name and port pairs in comma-separated list.

property:: `hostPorts`
default:: `localhost`

Examples:

[source]
----
hostPorts="node0,node1"
hostPorts="node0:1234,node1:4321"
----

=== Password

The Redis cluster `AUTH` password.

property:: `password`
default:: _none_

=== Client Connection Timeout

The Redis cluster client connection timeout in milliseconds.

property:: `connectionTimeout`
default:: `2000`

=== Client Connection Pool Size

The Redis cluster client connection pool size.

property:: `connectionPoolSize`
default:: `8`
